const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/components/CalibrationLaunchModal.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// Detect line ending
const CRLF = content.includes('\r\n') ? '\r\n' : '\n';
const lines = content.split(CRLF);

// Find start line: "          {/* Part 2 Configuration"
const startIdx = lines.findIndex(l => l.includes('Part 2 Configuration: Mask and Structure'));
// Find end line: the closing ")}" of the config block — it's the line after the closing </div> at same nesting level
// It ends at the line that has "          )}" after the big config div
// We'll search forward from startIdx for the pattern: just "          )}" alone
let endIdx = -1;
for (let i = startIdx + 1; i < lines.length; i++) {
  if (lines[i].trim() === ')}' && lines[i].includes('          )}')) {
    endIdx = i;
    break;
  }
}

if (startIdx < 0 || endIdx < 0) {
  console.error('Could not find config block boundaries:', startIdx, endIdx);
  // Show context
  lines.slice(380, 400).forEach((l, i) => console.log(380 + i, JSON.stringify(l)));
  process.exit(1);
}

console.log(`Config block: lines ${startIdx + 1} to ${endIdx + 1}`);

// Build the new config panel
const nl = CRLF;
const newBlock = [
  `          {/* Configuration Panel — collapsible */}`,
  `          {!isSubmitted && (`,
  `            <div className="flex-shrink-0 border-b border-slate-200">`,
  ``,
  `              {/* Toggle handle */}`,
  `              <div`,
  `                className="bg-slate-50 px-6 py-2.5 flex items-center justify-between cursor-pointer hover:bg-slate-100 transition-colors select-none"`,
  `                onClick={() => setIsConfigOpen(o => !o)}`,
  `              >`,
  `                <div className="flex items-center gap-3">`,
  `                  <ClipboardList className="w-4 h-4 text-indigo-500" />`,
  `                  <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">`,
  `                    Configurações de Lançamento`,
  `                  </span>`,
  `                  {selectedMask && (`,
  `                    <span className="bg-indigo-100 text-indigo-700 text-[9px] font-black px-2 py-0.5 rounded-full">`,
  `                      {selectedMask.title}`,
  `                    </span>`,
  `                  )}`,
  `                  {groups.length > 0 && (`,
  `                    <span className="bg-emerald-100 text-emerald-700 text-[9px] font-black px-2 py-0.5 rounded-full">`,
  `                      ✓ Estrutura gerada`,
  `                    </span>`,
  `                  )}`,
  `                </div>`,
  `                <span className={\`text-slate-400 text-xs transition-transform duration-200 \${isConfigOpen ? 'rotate-180' : ''}\`}>▼</span>`,
  `              </div>`,
  ``,
  `              {/* Collapsible body */}`,
  `              {isConfigOpen && (`,
  `                <div className="bg-white px-6 py-4 space-y-4">`,
  ``,
  `                  {/* Row 1: Mask + Resolution + Generate */}`,
  `                  <div className="flex flex-wrap gap-3 items-end">`,
  `                    <div className="flex-1 min-w-[200px] space-y-1">`,
  `                      <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest">Modelo de Cálculo (Máscara)</label>`,
  `                      <select`,
  `                        value={selectedMask?.id || ''}`,
  `                        onChange={(e) => {`,
  `                          const maskId = e.target.value;`,
  `                          const m = certificateMasks.find(mask => mask.id === maskId) || null;`,
  `                          setSelectedMask(m);`,
  `                          if (m) {`,
  `                            const p = m.numberOfPoints || 5;`,
  `                            const r = m.repetitions || 3;`,
  `                            setPointsCount(p);`,
  `                            setRowsCount(r);`,
  `                            setGroupSettings(m.measurementGroups.map(mg => ({`,
  `                              points: mg.numberOfPoints ?? p,`,
  `                              rows: mg.repetitions ?? r`,
  `                            })));`,
  `                            if (groups.length === 0) {`,
  `                              generateStructureTemplate(m, p, r);`,
  `                            } else if (confirm('Alterar a máscara irá resetar os dados preenchidos. Continuar?')) {`,
  `                              generateStructureTemplate(m, p, r);`,
  `                            }`,
  `                          }`,
  `                          setIsDirty(true);`,
  `                        }}`,
  `                        className="w-full bg-white border border-slate-200 p-2.5 rounded-xl focus:ring-2 focus:ring-indigo-300 outline-none font-bold text-sm shadow-sm"`,
  `                      >`,
  `                        <option value="">-- Selecione uma Máscara --</option>`,
  `                        {certificateMasks.map(mask => (`,
  `                          <option key={mask.id} value={mask.id}>{mask.title}</option>`,
  `                        ))}`,
  `                      </select>`,
  `                    </div>`,
  `                    <div className="flex items-center gap-2 bg-amber-50 px-3 py-2 rounded-xl border border-amber-100 flex-shrink-0">`,
  `                      <Info className="w-3.5 h-3.5 text-amber-600" />`,
  `                      <span className="text-[9px] font-black text-amber-700 uppercase tracking-widest">Resolução:</span>`,
  `                      <input`,
  `                        type="number"`,
  `                        step="any"`,
  `                        value={instrumentResolution}`,
  `                        onChange={e => {`,
  `                          const val = parseFloat(e.target.value) || 0;`,
  `                          setInstrumentResolution(val);`,
  `                          runCalculations(groups);`,
  `                        }}`,
  `                        className="w-20 bg-white border border-amber-200/50 p-1.5 rounded-lg font-black text-sm text-center text-amber-700 outline-none"`,
  `                      />`,
  `                    </div>`,
  `                    <button`,
  `                      onClick={handleGenerateStructure}`,
  `                      className="flex-shrink-0 px-6 py-2.5 bg-indigo-600 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-indigo-700 transition-all shadow-md"`,
  `                    >`,
  `                      Gerar Estrutura`,
  `                    </button>`,
  `                  </div>`,
  ``,
  `                  {/* Row 2: Per-group pontosxreps grid */}`,
  `                  {selectedMask && (`,
  `                    <div className="space-y-1">`,
  `                      <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest">Pontos × Repetições por Estrutura</label>`,
  `                      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-2">`,
  `                        {selectedMask.measurementGroups.map((mg, mgi) => (`,
  `                          <div key={mgi} className="flex items-center gap-1.5 bg-slate-50 border border-slate-200 rounded-xl px-2 py-1.5 hover:border-indigo-200 transition-colors">`,
  `                            <span className="text-[9px] font-bold text-slate-600 truncate flex-1" title={mg.name}>{mg.name}</span>`,
  `                            <input`,
  `                              type="number"`,
  `                              title="Pontos"`,
  `                              min="1"`,
  `                              value={groupSettings[mgi]?.points ?? mg.numberOfPoints ?? pointsCount}`,
  `                              onChange={e => setGroupSettings(prev => {`,
  `                                const next = [...prev];`,
  `                                next[mgi] = { ...next[mgi], points: parseInt(e.target.value) || 1 };`,
  `                                return next;`,
  `                              })}`,
  `                              className="w-9 bg-white border border-indigo-200 p-0.5 rounded-lg font-black text-xs text-center text-indigo-700 outline-none focus:ring-1 focus:ring-indigo-300"`,
  `                            />`,
  `                            <span className="text-slate-300 text-[10px]">×</span>`,
  `                            <input`,
  `                              type="number"`,
  `                              title="Repetições"`,
  `                              min="1"`,
  `                              value={groupSettings[mgi]?.rows ?? mg.repetitions ?? rowsCount}`,
  `                              onChange={e => setGroupSettings(prev => {`,
  `                                const next = [...prev];`,
  `                                next[mgi] = { ...next[mgi], rows: parseInt(e.target.value) || 1 };`,
  `                                return next;`,
  `                              })}`,
  `                              className="w-9 bg-white border border-slate-200 p-0.5 rounded-lg font-black text-xs text-center outline-none focus:ring-1 focus:ring-slate-300"`,
  `                            />`,
  `                          </div>`,
  `                        ))}`,
  `                      </div>`,
  `                    </div>`,
  `                  )}`,
  ``,
  `                  {/* Row 3: Standards as horizontal chips */}`,
  `                  {standardDetails.length > 0 && (`,
  `                    <div className="space-y-1">`,
  `                      <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest">Padrões Qualificados (U & k)</label>`,
  `                      <div className="flex gap-2 overflow-x-auto pb-1">`,
  `                        {standardDetails.map((detail, idx) => {`,
  `                          const si = standardInstruments.find(s => s.id === detail.instrumentId);`,
  `                          return (`,
  `                            <div key={idx} className="flex-shrink-0 flex items-center gap-3 bg-slate-50 border border-slate-200 rounded-2xl px-3 py-2 min-w-[220px]">`,
  `                              <div className="w-8 h-8 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">`,
  `                                <Shield size={14} className="text-indigo-600" />`,
  `                              </div>`,
  `                              <div className="min-w-0 flex-1">`,
  `                                <p className="text-[9px] font-black text-slate-700 uppercase truncate">{si?.identificacao || 'Padrão'}</p>`,
  `                                <p className="text-[8px] text-slate-400 truncate">{si?.nome}</p>`,
  `                              </div>`,
  `                              <div className="flex gap-1.5 flex-shrink-0">`,
  `                                <div className="relative">`,
  `                                  <span className="absolute -top-1.5 left-1 text-[6px] font-black text-indigo-500 bg-white px-1 rounded-full border border-indigo-100 z-10">U</span>`,
  `                                  <input`,
  `                                    type="number"`,
  `                                    title="Incerteza"`,
  `                                    value={detail.declaredU}`,
  `                                    onChange={e => {`,
  `                                      const val = parseFloat(e.target.value) || 0;`,
  `                                      const updated = [...standardDetails];`,
  `                                      updated[idx].declaredU = val;`,
  `                                      setStandardDetails(updated);`,
  `                                      runCalculations(groups);`,
  `                                    }}`,
  `                                    className="w-16 bg-white border border-indigo-100 p-1 pt-3 rounded-lg text-xs font-black text-center text-indigo-700 outline-none focus:ring-1 focus:ring-indigo-300"`,
  `                                  />`,
  `                                </div>`,
  `                                <div className="relative">`,
  `                                  <span className="absolute -top-1.5 left-1 text-[6px] font-black text-indigo-500 bg-white px-1 rounded-full border border-indigo-100 z-10">k</span>`,
  `                                  <input`,
  `                                    type="number"`,
  `                                    step="0.01"`,
  `                                    title="Fator k"`,
  `                                    value={detail.certificateK}`,
  `                                    onChange={e => {`,
  `                                      const val = parseFloat(e.target.value) || 0;`,
  `                                      const updated = [...standardDetails];`,
  `                                      updated[idx].certificateK = val;`,
  `                                      setStandardDetails(updated);`,
  `                                      runCalculations(groups);`,
  `                                    }}`,
  `                                    className="w-16 bg-white border border-slate-100 p-1 pt-3 rounded-lg text-xs font-black text-center outline-none focus:ring-1 focus:ring-slate-300"`,
  `                                  />`,
  `                                </div>`,
  `                              </div>`,
  `                            </div>`,
  `                          );`,
  `                        })}`,
  `                      </div>`,
  `                    </div>`,
  `                  )}`,
  ``,
  `                </div>`,
  `              )}`,
  `            </div>`,
  `          )}`
].join(nl);

// Replace lines from startIdx to endIdx (inclusive)
lines.splice(startIdx, endIdx - startIdx + 1, newBlock);
fs.writeFileSync(filePath, lines.join(CRLF), 'utf8');
console.log('SUCCESS: Config panel fully redesigned.');
